#!/usr/bin/env node
// Public tracked packaging validation. No daemon, .env, deployment or media action.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root,name),'utf8');
const env = Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('VIPTV_')));
env.VIPTV_AUTH_ORIGIN = 'https://fixture.invalid';
function config(extra={}) {
  return JSON.parse(execFileSync('docker',['compose','--env-file','/dev/null','--project-directory',root,'-f',path.join(root,'compose.yaml'),'config','--format','json'],{env:{...env,...extra},encoding:'utf8'}));
}
const compose = config();
const service = compose.services.viptv;
assert.equal(service.environment.VIPTV_AUTH_ORIGIN,'https://fixture.invalid');
assert.equal(service.user,'10001:10001');
assert.equal(service.read_only,true);
assert.equal(service.init,true);
assert(service.cap_drop.includes('ALL'));
assert(service.security_opt.includes('no-new-privileges:true'));
assert.equal(service.privileged,undefined);
assert.equal(service.devices,undefined);
assert.equal(service.network_mode,undefined);
assert.equal(compose.volumes.viptv_data.name,'viptv_viptv_data');
assert(service.volumes.some(volume=>volume.source==='viptv_data'&&volume.target==='/data'));
assert(!service.tmpfs.some(value=>value.startsWith('/cache')));
assert(service.tmpfs.some(value=>value.startsWith('/tmp:')&&value.includes('size=64m')&&value.includes('uid=10001')));
const retired = ['VIPTV_MEDIA_DIR','VIPTV_FFMPEG','VIPTV_FFPROBE','VIPTV_MAX_SESSIONS','VIPTV_SESSION_TTL','VIPTV_MEDIA_CORS_ORIGINS','VIPTV_DIRECT_PLAY','VIPTV_BROWSER_PREPARATION','VIPTV_QSV_DEVICE','VIPTV_VAAPI_DEVICE','VIPTV_WARP_PROXY'];
for(const key of retired)assert.equal(service.environment[key],undefined,key);
assert(service.environment.VIPTV_SECRETS_KEYRING == null,'Absent keyring must remain an unresolved/omitted value, never empty JSON');
const fixtureKeyring='synthetic-private-value-not-a-real-keyring';
assert.equal(config({VIPTV_SECRETS_KEYRING:fixtureKeyring}).services.viptv.environment.VIPTV_SECRETS_KEYRING,fixtureKeyring);
const backend = ['server/src/main.rs','server/src/auth/schema.rs','server/src/auth/middleware.rs','server/src/secret_store.rs'].map(read).join('\n');
for(const key of Object.keys(service.environment))assert(backend.includes('"'+key+'"'),key+' has no backend reader');
const dockerfile=read('Dockerfile');
const runtime=dockerfile.slice(dockerfile.lastIndexOf('FROM '));
assert(/^USER 10001:10001$/m.test(runtime));
assert(/^ENTRYPOINT \["\/usr\/local\/bin\/viptv-server"\]$/m.test(runtime));
assert(runtime.includes('ca-certificates curl'));
assert(!runtime.includes('ffmpeg')&&!runtime.includes('intel-media')&&!runtime.includes('/cache'));
assert(runtime.includes('/api/health'));
assert(dockerfile.includes('cargo build --release --locked'));
assert(dockerfile.includes('npm ci --no-audit --no-fund'));
assert(!read('server/Cargo.toml').includes('viptv-playback-engine'));
assert(!fs.existsSync(path.join(root,'server/playback-engine')));
for(const name of ['compose.warp.yaml','compose.qsv.yaml','compose.validation.yaml','compose.validation.qsv.yaml','deploy/warp/Dockerfile','scripts/qsv-frame-check.py','scripts/benchmark-transcoder.py','tests/Dockerfile.integration','tests/smoke.py','tests/sustained_playback.py','tests/incremental_providers.py','tests/live_deployment_check.py'])assert(!fs.existsSync(path.join(root,name)),name+' is a retired active hook');
assert(!read('compose.yaml').includes('/var/run/docker.sock'));
const ignored=read('.dockerignore').split(/\r?\n/);
for(const pattern of ['**','server/target/','dashboard/node_modules/','tv/node_modules/'])assert(ignored.includes(pattern));
assert(fs.statSync(path.join(root,'server/Cargo.lock')).isFile());
console.log('PASS Compose syntax, origin, optional keyring, nonroot/read-only security and named-volume preservation');
console.log('PASS engine-free image/environment, runtime readers and restricted build context');
console.log('Static only: no daemon, private deployment env, image build, provider or device qualification.');
