User nobody
Group nogroup
Port 8899
Listen 0.0.0.0
Timeout 60
LogFile "/dev/stderr"
LogLevel Critical
PidFile "/tmp/viptv-egress.pid"
MaxClients 64
Allow 127.0.0.1
Allow 10.0.0.0/8
Allow 172.16.0.0/12
Allow 192.168.0.0/16
DisableViaHeader Yes
ConnectPort 443
ConnectPort 80
ConnectPort 8080
